### PR TITLE
- added gulp build system

### PR DESCRIPTION
**Pull request by worldspawn**
- added package.json
- moved bower main files to build output in root
- wrote 4 tests

Let me know if theres any issues/missed instructions

This annotates the source file automatically (ng-annotate) and puts the annotated version in the root. It also puts an uglified version of that in the root with .min.js as extension. The bower.json main file has changed to point to /multi-transclude.js. **This means if u change `src/*.js` you must run gulp to update the release files**

I've added .jshintrc file too which is enforced by the gulp build process.

so you need to do:
`npm install`
`bower install`

then run `gulp`

and you get some output like:

```
[15:25:15] Using gulpfile ~\Source\ng-multi-transclude\gulpfile.js
[15:25:15] Starting 'preparetesthtml'...
[15:25:15] Starting 'annotate'...
[15:25:15] all files 3.8 kB
[15:25:15] Finished 'annotate' after 323 ms
[15:25:15] Starting 'jshint'...
[15:25:16] Starting 'compress'...
[15:25:16] Starting 'concat'...
[15:25:16] Finished 'jshint' after 795 ms
[15:25:16] all files 1.09 kB
[15:25:16] Finished 'preparetesthtml' after 1.47 s
[15:25:16] Starting 'preparetestfiles'...
[15:25:16] Finished 'preparetestfiles' after 32 ms
[15:25:16] Starting 'test'...
[15:25:17] all files 3.8 kB
[15:25:17] Finished 'concat' after 756 ms
[15:25:17] all files 1.34 kB
[15:25:17] Finished 'compress' after 1.06 s
[15:25:17] Starting Karma server...
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Windows 8)]: Connected on socket ePnhzNCGxHspJJuBeiGF with id 11689969
PhantomJS 1.9.8 (Windows 8): Executed 4 of 4 SUCCESS (0.022 secs / 0.05 secs)

=============================== Coverage summary ===============================
Statements   : 85.11% ( 40/47 )
Branches     : 55.56% ( 10/18 )
Functions    : 85.71% ( 12/14 )
Lines        : 85.11% ( 40/47 )
================================================================================
[15:25:22] Finished 'test' after 5.6 s
[15:25:22] Starting 'build'...
[15:25:22] Finished 'build' after 28 μs
[15:25:22] Starting 'default'...
[15:25:22] Finished 'default' after 40 μs
```

### CODE REVIEW

**Comment by worldspawn** [comment]
I tried to get jasmine2 going... I've only ever done it with protractor and not karma. Theres no solid instructions on how to make that happen. I installed the npm package as instructed but i still dont seem to be able to call beforeAll or any other jasmine 2 things. Anyway...

**Comment by zachsnow** [comment]
Wow, lots of goods here! I will look at this over the weekend and hopefully get it into `master`. Also it will be good to get a failing test-case for the `ng-if` issues in #22 so I can rewrite the module to support linking multiple times. Only thing I might change is removing `ng-annotate` because there's so little to annotate...

Thanks!

**Comment by zachsnow** [comment]
Sorry for the delay, work has intruded but I am eager to look at this.

**Comment by zachsnow** [comment]
I updated this in #30 accidentally instead of here, but please have a look @worldspawn.

**Pull request closed without merging**
